Tabs to Spaces for Support Files

diff --git a/deploy/calc-tag b/deploy/calc-tag
--- a/deploy/calc-tag
+++ b/deploy/calc-tag
@@ -16,86 +16,86 @@ declare -r VERSION_REGEX='([0-9]+\.[0-9]+\.[0-9]+)(\..*|-[a-z]+-[0-9]+|)'
 ##
 # Print the help for this script.
 printHelp() {
-	cat <<- 'EOF'
-		usage: calc-tag --meta-tag <alpha|beta|rc> [--build-number <build_number>]
+    cat <<- 'EOF'
+        usage: calc-tag --meta-tag <alpha|beta|rc> [--build-number <build_number>]
 
-		options:
-	EOF
-	column -ts: <<- 'EOF'
-		  -h|--help:(this information)
-		  -m|--meta-tag=:(Release meta tag: alpha|beta|rc)
-		  -b|--build-number=:(Release build number)
-	EOF
-	echo
+        options:
+    EOF
+    column -ts: <<- 'EOF'
+          -h|--help:(this information)
+          -m|--meta-tag=:(Release meta tag: alpha|beta|rc)
+          -b|--build-number=:(Release build number)
+    EOF
+    echo
 }
 
 ##
 # Process the commandline options in whatever order
 processOpts() {
-	while [[ $1 ]]; do
-		case $1 in
-			-h|--help)
-				printHelp
-				exit 0
-				;;
-			-m|--meta-tag)
-				metaTag="$2"
-				shift
-				;;
-			-m=*|--meta-tag=*)
-				metaTag="${1#*=}"
-				;;
-			-b|--build-number)
-				buildNumber="$2"
-				shift
-				;;
-			-b=*|--build-number=*)
-				buildNumber="${1#*=}"
-				;;
-			*)
-				printHelp
-				exit 1
-				;;
-		esac
-		shift
-	done
+    while [[ $1 ]]; do
+        case $1 in
+            -h|--help)
+                printHelp
+                exit 0
+                ;;
+            -m|--meta-tag)
+                metaTag="$2"
+                shift
+                ;;
+            -m=*|--meta-tag=*)
+                metaTag="${1#*=}"
+                ;;
+            -b|--build-number)
+                buildNumber="$2"
+                shift
+                ;;
+            -b=*|--build-number=*)
+                buildNumber="${1#*=}"
+                ;;
+            *)
+                printHelp
+                exit 1
+                ;;
+        esac
+        shift
+    done
 
-	if ! has "$metaTag" 'alpha' 'beta' 'rc'; then
-		echo "Error: meta-tag must be one of ('alpha', 'beta', 'rc')" >&2
-		printHelp
-		exit 1
-	fi
+    if ! has "$metaTag" 'alpha' 'beta' 'rc'; then
+        echo "Error: meta-tag must be one of ('alpha', 'beta', 'rc')" >&2
+        printHelp
+        exit 1
+    fi
 }
 
 ##
 # generate the tag
 main() {
-	local metaTag
-	local buildNumber
-	local newTag
-	local oldTag
-	local releaseVersion
+    local metaTag
+    local buildNumber
+    local newTag
+    local oldTag
+    local releaseVersion
 
-	processOpts "$@"
-	oldTag=$(git describe --match *.*.* --abbrev=0 2>/dev/null)
-	releaseVersion=$(echo $oldTag | sed -rn "s/$VERSION_REGEX/\1/p")
-	if [[ -z $releaseVersion ]]; then
-		echo "Error: a tag must already exist that matches $VERSION_REGEX" >&2
-		exit 1
-	fi
+    processOpts "$@"
+    oldTag=$(git describe --match *.*.* --abbrev=0 2>/dev/null)
+    releaseVersion=$(echo $oldTag | sed -rn "s/$VERSION_REGEX/\1/p")
+    if [[ -z $releaseVersion ]]; then
+        echo "Error: a tag must already exist that matches $VERSION_REGEX" >&2
+        exit 1
+    fi
 
-	if [[ -z "$buildNumber" ]]; then
-		buildNumber=$(git describe --tags --match *.*.*[.-]* --abbrev=0)
-		buildNumber=$((${buildNumber##*[.-]} + 1 ))
-	fi
+    if [[ -z "$buildNumber" ]]; then
+        buildNumber=$(git describe --tags --match *.*.*[.-]* --abbrev=0)
+        buildNumber=$((${buildNumber##*[.-]} + 1 ))
+    fi
 
-	newTag="$releaseVersion-$metaTag-$buildNumber"
-	if [[ ! -z $(git describe --abbrev=0 --exact-match $newTag 2>/dev/null) ]]; then
-		echo "Error: $newTag already exists." >&2
-		exit 1
-	fi
+    newTag="$releaseVersion-$metaTag-$buildNumber"
+    if [[ ! -z $(git describe --abbrev=0 --exact-match $newTag 2>/dev/null) ]]; then
+        echo "Error: $newTag already exists." >&2
+        exit 1
+    fi
 
-	echo "$newTag"
+    echo "$newTag"
 }
 
 . deploy/utils
diff --git a/tests/runTests b/tests/runTests
--- a/tests/runTests
+++ b/tests/runTests
@@ -1,8 +1,8 @@
 #!/bin/bash -e
 
 if [[ ! $MAGEPKG ]]; then
-	printf 'Expected MAGEPKG to define where to find the desired Magento package file.\n' >&2
-	exit 1
+    printf 'Expected MAGEPKG to define where to find the desired Magento package file.\n' >&2
+    exit 1
 fi
 db_name='mage'
 db_pass=$(dd if=/dev/urandom bs=32 count=1 | base64)
@@ -11,7 +11,7 @@ db_user='root'
 
 (
 if cd build; then
-	tar -xf "$MAGEPKG"
+    tar -xf "$MAGEPKG"
 fi
 )
 
@@ -24,60 +24,60 @@ xmlstarlet ed -u /config/global/resources/default_setup/connection/dbname -v "$d
 # Set up ecomdev testing for EB2C
 #
 (
-	if mkdir -p mysql/data && cd mysql; then
-		[[ -f mysql.pid ]] && kill $(<mysql.pid)
-		client_opts=(
-			--no-defaults
-			--socket="$db_sock"
-		)
-		server_opts=(
-			"${client_opts[@]}"
-			--basedir="$(nix-store -qR $(type -P mysqld) | tail -n 1)"
-			--datadir="$PWD/data"
-			--log-error="$PWD/error.log"
-			--pid-file="$PWD/mysql.pid"
-			--skip-networking
-		)
-		mysql_install_db "${server_opts[@]}"
-		mysqld_safe "${server_opts[@]}" &
-		counter=6
-		echo 'Waiting for mysql to come up.'
-		until mysql "${client_opts[@]}" -e 'SELECT TRUE;' 2>/dev/null; do
-			sleep 1
-			if (( counter-- < 1 )); then
-				printf 'Gave up waiting for MySQL to start.\n' >&2
-				exit 1
-			fi
-		done
-		mysqladmin "${client_opts[@]}" -u root password "$db_pass" create "$db_name"
-	fi
+    if mkdir -p mysql/data && cd mysql; then
+        [[ -f mysql.pid ]] && kill $(<mysql.pid)
+        client_opts=(
+            --no-defaults
+            --socket="$db_sock"
+        )
+        server_opts=(
+            "${client_opts[@]}"
+            --basedir="$(nix-store -qR $(type -P mysqld) | tail -n 1)"
+            --datadir="$PWD/data"
+            --log-error="$PWD/error.log"
+            --pid-file="$PWD/mysql.pid"
+            --skip-networking
+        )
+        mysql_install_db "${server_opts[@]}"
+        mysqld_safe "${server_opts[@]}" &
+        counter=6
+        echo 'Waiting for mysql to come up.'
+        until mysql "${client_opts[@]}" -e 'SELECT TRUE;' 2>/dev/null; do
+            sleep 1
+            if (( counter-- < 1 )); then
+                printf 'Gave up waiting for MySQL to start.\n' >&2
+                exit 1
+            fi
+        done
+        mysqladmin "${client_opts[@]}" -u root password "$db_pass" create "$db_name"
+    fi
 )
 
 (
 if cd build/magento; then
-	# Run the Magento installer.
-	php -f install.php -- \
-		--admin_email 'foo@bar.com' \
-		--admin_firstname 'First' \
-		--admin_frontname 'admin' \
-		--admin_lastname 'Last' \
-		--admin_password 'testing123' \
-		--admin_username 'admin' \
-		--db_host "$db_sock" \
-		--db_name "$db_name" \
-		--db_pass "$db_pass" \
-		--db_user "$db_user" \
-		--default_currency 'USD' \
-		--license_agreement_accepted 'yes' \
-		--locale 'en_US' \
-		--secure_base_url 'https://example.com' \
-		--session_save 'files' \
-		--skip_url_validation 'yes' \
-		--timezone 'America/New_York' \
-		--url 'http://example.com' \
-		--use_rewrites 'yes' \
-		--use_secure 'yes' \
-		--use_secure_admin 'yes'
+    # Run the Magento installer.
+    php -f install.php -- \
+        --admin_email 'foo@bar.com' \
+        --admin_firstname 'First' \
+        --admin_frontname 'admin' \
+        --admin_lastname 'Last' \
+        --admin_password 'testing123' \
+        --admin_username 'admin' \
+        --db_host "$db_sock" \
+        --db_name "$db_name" \
+        --db_pass "$db_pass" \
+        --db_user "$db_user" \
+        --default_currency 'USD' \
+        --license_agreement_accepted 'yes' \
+        --locale 'en_US' \
+        --secure_base_url 'https://example.com' \
+        --session_save 'files' \
+        --skip_url_validation 'yes' \
+        --timezone 'America/New_York' \
+        --url 'http://example.com' \
+        --use_rewrites 'yes' \
+        --use_secure 'yes' \
+        --use_secure_admin 'yes'
 fi
 )
 xdebug_extension='lib/php/extensions/xdebug.so';
